# Generated by Django 5.2.5 on 2025-08-08 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('avg_inference_time', models.FloatField()),
                ('max_inference_time', models.FloatField()),
                ('min_inference_time', models.FloatField()),
                ('total_inferences', models.IntegerField()),
                ('avg_confidence', models.FloatField()),
                ('avg_quality_score', models.FloatField()),
                ('class_distribution', models.JSONField(default=dict)),
                ('error_rate', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(blank=True, null=True)),
                ('gpu_utilization', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QualityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_confidence', 'Low Confidence'), ('model_drift', 'Model Drift'), ('performance_degradation', 'Performance Degradation'), ('anomaly_detection', 'Anomaly Detection'), ('system_error', 'System Error')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('alert_data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='scanrecord',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='detections_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='has_errors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='mature_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='model_version',
            field=models.CharField(default='unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='not_mature_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='over_ripe_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='overall_quality_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='processing_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='quality_metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='quality_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='ripe_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='scanrecord',
            index=models.Index(fields=['user', '-timestamp'], name='api_scanrec_user_id_05fcf4_idx'),
        ),
        migrations.AddIndex(
            model_name='scanrecord',
            index=models.Index(fields=['model_version'], name='api_scanrec_model_v_2ae059_idx'),
        ),
        migrations.AddIndex(
            model_name='scanrecord',
            index=models.Index(fields=['overall_quality_score'], name='api_scanrec_overall_9c2a17_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodelperformance',
            index=models.Index(fields=['model_version', '-timestamp'], name='api_mlmodel_model_v_c3b2dd_idx'),
        ),
        migrations.AddField(
            model_name='qualityalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualityalert',
            name='scan_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.scanrecord'),
        ),
        migrations.AddIndex(
            model_name='qualityalert',
            index=models.Index(fields=['alert_type', '-timestamp'], name='api_quality_alert_t_ce638f_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityalert',
            index=models.Index(fields=['severity', '-timestamp'], name='api_quality_severit_e58758_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityalert',
            index=models.Index(fields=['is_resolved'], name='api_quality_is_reso_5fd1fa_idx'),
        ),
    ]
